//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Denuncias> Denuncias { get; set; }
        public virtual DbSet<DonacionesMonetarias> DonacionesMonetarias { get; set; }
        public virtual DbSet<Motivo> Motivo { get; set; }
        public virtual DbSet<Propuestas> Propuestas { get; set; }
        public virtual DbSet<PropuestasDonacionesHorasTrabajo> PropuestasDonacionesHorasTrabajo { get; set; }
        public virtual DbSet<PropuestasDonacionesInsumos> PropuestasDonacionesInsumos { get; set; }
        public virtual DbSet<PropuestasDonacionesMonetarias> PropuestasDonacionesMonetarias { get; set; }
        public virtual DbSet<PropuestasReferencias> PropuestasReferencias { get; set; }
        public virtual DbSet<PropuestasValoraciones> PropuestasValoraciones { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<DonacionesHorasTrabajo> DonacionesHorasTrabajo { get; set; }
        public virtual DbSet<DonacionesInsumos> DonacionesInsumos { get; set; }
    }
}
